find_package(Boost REQUIRED)
find_library(BOOST_URL_LIBRARY NAMES boost_url REQUIRED)
find_library(BOOST_PROGRAM_OPTIONS_LIBRARY NAMES boost_program_options REQUIRED)
find_library(BOOST_JSON_LIBRARY NAMES boost_json REQUIRED)

set(MEDIA_SERVER_BOOST_LIBS
    ${BOOST_URL_LIBRARY}
    ${BOOST_JSON_LIBRARY}
)

set(MEDIA_SERVER_BOOST_PROGRAM_OPTIONS_LIB
    ${BOOST_PROGRAM_OPTIONS_LIBRARY}
)
